### ISSUE TITLE
SBML files not valid

### ISSUE THREAD

**Issue by fairquestion** [chaplenf/microBiome-v2.1#1]
Dear all,

The SBML files iFC578.xml iFC579.xml are not recognized by SBML validator (http://bigg.ucsd.edu/validator/app) (http://sbml.org/Facilities/Validator/validate.jsp) both validators state that your .xml files are not valid SBMLs. It also produces several errors when they are imported into OptFlux3. 

Would be great if you can provide validated SBML files.

Thanks in advance,
Fair

**Comment by zoey-rw** [comment]
@chaplenf it looks like the newer files (from Oct 2019) are also not valid SBML. Do you know if anyone has updated either of the models?

Thank you,
Zoey

**Comment by chaplenf** [comment]
> @chaplenf it looks like the newer files (from Oct 2019) are also not valid SBML. Do you know if anyone has updated either of the models?
> 
> Thank you, Zoey

Zoey,
The student that worked on this project has graduated and I am unaware of others have updated the model.  Apologies.
Frank Chaplen
